config/routes.rb
Rails.application.routes.draw do
  root :to => "frontpage#index"
  
  match 'home' => 'home#index', :as => :home
  match 'home' => 'home#index', :as => :user_root # devise after_sign_in_path_for
  match 'explore(/:section)' => 'explore#index', :as => :explore
  match 'search' => 'search#index', :as => :search

  # Social Stream subjects configured in config/initializers/social_stream.rb
  route_subjects do
    resources :contacts
    resource :like
    resource :profile
    resources :activities

    # Nested Social Stream objects configured in config/initializers/social_stream.rb
    #
    # /users/demo/posts
    (SocialStream.objects - [ :actor ]).each do |object|
      resources object.to_s.pluralize do
        get 'search', :on => :collection
      end
    end

    # Repository models are configured in config/initializers/social_stream.rb
    if SocialStream.repository_models.present?
      resource :repository do
        get 'search', on: :collection
      end
    end
  end

  resources :actors, only: [ :index ]

  # Get information about current_subject
  match 'user'    => 'users#current', format: :json

  match 'profile' => 'profiles#show'

  # Social Stream objects configured in config/initializers/social_stream.rb
  #
  # /posts
  (SocialStream.objects - [ :actor ]).each do |object|
    resources object.to_s.pluralize do
      get 'search', :on => :collection
    end
  end

  resources :comments

  # Repository models are configured in config/initializers/social_stream.rb
  if SocialStream.repository_models.present?
    resource :repository do
      get 'search', on: :collection
    end
  end

  resources :contacts do
    collection do
      get 'suggestion'
      get 'pending'
    end
  end

  namespace "relation" do
    resources :customs
  end

  resources :permissions

  resources :activity_actions

  resource :representation
  
  resources :settings do
    collection do
      put 'update_all'
    end
  end

  resources :messages

  resources :conversations

  resources :invitations
  
  resources :notifications do
    collection do
      put 'update_all'
    end
  end

  resources :activities do
    resource :like
  end

  get 'home/activities' => 'activities#index', as: :home_activities, defaults: { section: 'home' }

  get 'audience/index', :as => :audience
  
  match 'ties' => 'ties#index', :as => :ties
  
  match 'tags' => 'tags#index', :as => 'tags'
  
  ##API###
  match 'api/keygen' => 'api#create_key', :as => :api_keygen
  match 'api/user/:id' => 'api#users', :as => :api_user
  match 'api/me' => 'api#users', :as => :api_me
  match 'api/me/home/' => 'api#activity_atom_feed', :format => 'atom', :as => :api_my_home

  match 'api/me/contacts' => 'contacts#index', :format => 'json', :as => :api_contacts
  ##/API##
 
  #Background tasks
  constraints SocialStream::Routing::Constraints::Resque.new do
    mount Resque::Server, :at => "/resque"
  end
end

app/views/toolbar/_contacts.html.erb
<section class="contacts-toolbar">
  <% if (cs = subject.contact_subjects(:direction => :sent).first(6)).present? %>
    <h4>
      <%= t('contacts') %>
    </h4>
    <span class="line"></span>
    <ul>
      <% cs.each do |contact| %>
        <li>
          <%= link_to(image_tag(contact.logo.url(:small), :alt => contact.name, :title => contact.name, :size => "small"), contact) %>
        </li>
      <% end %>
    </ul>
    <nav class="contacts-more">
      <%= link_to t("contact.view_all"), [ profile_subject, Contact.new ] %>
    </nav>    
  <% end %>
</section>

app/views/toolbar/_groups.html.erb
<section class="groups">
  <% if (gs = subject.contact_subjects(direction: :sent, type: :group) { |as| as.recent.first(6) }).present? %>
    <h4>
      <%= t('group.n', :count => subject.contact_subjects(:direction => :sent, type: :group).count) %>
    </h4>
    <span class="line"></span>
    <ul>
      <% gs.each do |g| %>
        <li>
          <%= link_to(image_tag(g.logo.url(:small), :alt => g.name, :title => g.name, :size => "small"), g) %>
        </li>
      <% end %>
    </ul>
    <nav class="groups-more">
      <%= link_to t("group.view_all"), polymorphic_path([ profile_subject, Contact.new ], type: :group) %>
    </nav>
  <% end %>
</section>

app/views/toolbar/_home.html.erb
<section id="toolbar" class="toolbar-home">
  <%= render partial: 'toolbar/subject' %>

  <%= render partial: 'toolbar/groups', locals: { subject: current_subject } %>
</section>

app/views/toolbar/_logo.html.erb
<div id="avatar_profile">
  <%= link_to image_tag(subject.logo.url(:medium), :alt => subject.name , :size => "150x150"), subject %>

  <% if subject == current_subject %>
    <div class="logo_menu logo_caption">    
      <%= link_to t('avatar.profile_change'), polymorphic_path([subject, :profile], section: :avatar)  %>
    </div>        
  <% end %>
</div>

<div class= "subject-name-phone">
  <%= subject.name %>
</div>

app/views/toolbar/_messages.html.erb
<section id="toolbar" class="toolbar-conversations">
  <nav class="toolbar_menu">
    <ul class="nav">
    <li>
      <%= link_to new_message_path do %>
        <i class='icon_message-new <%= 'active' if controller.action_name == 'new' %>'></i>
      <% end %>
    </li>
    <li>
      <%= link_to conversations_path(box: :inbox) do %>
        <i class='icon_message-inbox <%= 'active' if params[:box] == 'inbox' %>'></i> (<%= current_subject.unread_messages_count %>)
      <% end %>
    </li>
    <li>
      <%= link_to conversations_path(box: :sentbox) do %>
        <i class='icon_message-sentbox <%= 'active' if params[:box] == 'sentbox' %>'></i>
      <% end %>
    </li>
    <li>
      <%= link_to conversations_path(box: :trash) do %>
        <i class='icon_message-trash <%= 'active' if params[:box] == 'trash' %>'></i>
      <% end %>
    </li>
    </ul>
  </nav>
</section>

app/views/toolbar/_profile.html.erb
<section id="toolbar" class="toolbar-profile">
  <div class="user">
    <%= render partial: 'toolbar/logo',
               locals: { subject: subject } %>

    <% if current_subject.present? && subject != current_subject %>
    <div class="contact-button">
      <%= contact_button subject %>
    </div>
    <% end %>

  </div>

  <nav class="toolbar_menu">
    <ul class="nav">
    <li>
      <%= link_to [ subject, :profile ] do  %>
        <i class='icon_tool16-info'></i> <%= t 'menu.information' %>
      <% end %>
    </li>

    <% if SocialStream.repository_models.present? %>
      <li>
        <%= link_to [ subject, :repository ] do %>
          <i class='icon_navbar-resources'></i> <%= t 'repository.title' %>
        <% end %>
      </li>
    <% end %>

    <% if subject != current_subject %>
      <li>
        <%= link_to new_message_path(receiver: subject.slug) do %>
          <i class='icon_navbar-message'></i> <%= t 'mailboxer.send' %>
        <% end %>
      </li>
    <% end %>

    <div class="base_items"/>
    </ul>
  </nav>

  <%= render partial: 'toolbar/contacts', locals: { subject: subject } %>

  <%= render partial: 'toolbar/groups', locals: { subject: subject } %>
</section>

app/views/toolbar/_subject.html.erb
<div class="logo_home">
  <%= link_to (image_tag(current_subject.logo.url(:medium) , :size => "small", :alt => current_subject.name )), current_subject  %>
</div>
<h5>
  <%= link_to truncate_name(current_subject.name, :length => 80), current_subject %>
</h5>