config/routes.rb
Rails.application.routes.draw do
  root :to => "frontpage#index"
  
  match 'home' => 'home#index', :as => :home
  match 'home' => 'home#index', :as => :user_root # devise after_sign_in_path_for
  match 'explore(/:section)' => 'explore#index', :as => :explore
  match 'search' => 'search#index', :as => :search

  # Social Stream subjects configured in config/initializers/social_stream.rb
  route_subjects do
    resources :contacts
    resource :like
    resource :profile
    resources :activities

    # Nested Social Stream objects configured in config/initializers/social_stream.rb
    #
    # /users/demo/posts
    (SocialStream.objects - [ :actor ]).each do |object|
      resources object.to_s.pluralize do
        get 'search', :on => :collection
      end
    end

    # Repository models are configured in config/initializers/social_stream.rb
    if SocialStream.repository_models.present?
      resource :repository do
        get 'search', on: :collection
      end
    end
  end

  resources :actors, only: [ :index ]

  # Get information about current_subject
  match 'user'    => 'users#current', format: :json

  match 'profile' => 'profiles#show'

  # Social Stream objects configured in config/initializers/social_stream.rb
  #
  # /posts
  (SocialStream.objects - [ :actor ]).each do |object|
    resources object.to_s.pluralize do
      get 'search', :on => :collection
    end
  end

  resources :comments

  # Repository models are configured in config/initializers/social_stream.rb
  if SocialStream.repository_models.present?
    resource :repository do
      get 'search', on: :collection
    end
  end

  resources :contacts do
    collection do
      get 'suggestion'
      get 'pending'
    end
  end

  namespace "relation" do
    resources :customs
  end

  resources :permissions

  resources :activity_actions

  resource :representation
  
  resources :settings do
    collection do
      put 'update_all'
    end
  end

  resources :messages

  resources :conversations

  resources :invitations
  
  resources :notifications do
    collection do
      put 'update_all'
    end
  end

  resources :activities do
    resource :like
  end

  get 'home/activities' => 'activities#index', as: :home_activities, defaults: { section: 'home' }

  get 'audience/index', :as => :audience
  
  match 'ties' => 'ties#index', :as => :ties
  
  match 'tags' => 'tags#index', :as => 'tags'
  
  ##API###
  match 'api/keygen' => 'api#create_key', :as => :api_keygen
  match 'api/user/:id' => 'api#users', :as => :api_user
  match 'api/me' => 'api#users', :as => :api_me
  match 'api/me/home/' => 'api#activity_atom_feed', :format => 'atom', :as => :api_my_home

  match 'api/me/contacts' => 'contacts#index', :format => 'json', :as => :api_contacts
  ##/API##
 
  #Background tasks
  constraints SocialStream::Routing::Constraints::Resque.new do
    mount Resque::Server, :at => "/resque"
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :get_mailbox, :get_box, :get_actor
  before_filter :check_current_subject_in_conversation, :only => [:show, :update, :destroy]

  def index
    if @box.eql? "inbox"
      @conversations = @mailbox.inbox.page(params[:page]).per(9)
    elsif @box.eql? "sentbox"
      @conversations = @mailbox.sentbox.page(params[:page]).per(9)
    else
      @conversations = @mailbox.trash.page(params[:page]).per(9)
    end

    respond_to do |format|
      format.html { render @conversations if request.xhr? }
    end
  end

  def show
    if @box.eql? 'trash'
      @receipts = @mailbox.receipts_for(@conversation).trash
    else
      @receipts = @mailbox.receipts_for(@conversation).not_trash
    end
    render :action => :show
    @receipts.mark_as_read
  end

  def update
    if params[:untrash].present?
    @conversation.untrash(@actor)
    end

    if params[:reply_all].present?
      last_receipt = @mailbox.receipts_for(@conversation).last
      @receipt = @actor.reply_to_all(last_receipt, params[:body])
    end

    if @box.eql? 'trash'
      @receipts = @mailbox.receipts_for(@conversation).trash
    else
      @receipts = @mailbox.receipts_for(@conversation).not_trash
    end
    redirect_to :action => :show
    @receipts.mark_as_read

  end

  def destroy

    @conversation.move_to_trash(@actor)

    respond_to do |format|
      format.html {
        if params[:location].present? and params[:location] == 'conversation'
          redirect_to conversations_path(:box => :trash)
	else
          redirect_to conversations_path(:box => @box,:page => params[:page])
	end
      }
      format.js {
        if params[:location].present? and params[:location] == 'conversation'
          render :js => "window.location = '#{conversations_path(:box => @box,:page => params[:page])}';"
	else
          render 'conversations/destroy'
	end
      }
    end
  end

  private

  def get_mailbox
    @mailbox = current_actor.mailbox
  end

  def get_actor
    @actor = Actor.normalize(current_subject)
  end

  def get_box
    if params[:box].blank? or !["inbox","sentbox","trash"].include?params[:box]
      params[:box] = 'inbox'
    end

    @box = params[:box]
  end

  def check_current_subject_in_conversation
    @conversation = Conversation.find_by_id(params[:id])

    if @conversation.nil? or !@conversation.is_participant?(@actor)
      redirect_to conversations_path(:box => @box)
    return
    end
  end

end

app/views/conversations/_conversation.html.erb
<%= div_for(conversation, :class =>"#{ 'unread ' if conversation.is_unread?(@actor) }") do %>

  <div class="content_left">
    <div class="avatar">
      <%= link_to image_tag(conversation.last_sender.logo.url(:small),
                            :title => conversation.last_sender.name,
                            :alt => conversation.last_sender.name),
                  conversation.last_sender.subject %>
    </div>

    <header>
      <h5>
        <%= link_to truncate_name(conversation.last_sender.name), conversation.last_sender.subject %>
      </h5>
      <div class="date">
        <%= t('time.ago', :time => time_ago_in_words(conversation.updated_at)) %>
      </div>
    </header>

  </div>

  <div class="content_right">

    <div class="subject">
      <%= link_to(truncate(conversation.subject, :length => 55), conversation_path(conversation.id,:box => @box,:page => params[:page])) %>
    </div>

    <% unless @box.eql?'trash' %>
      <div class="action">
      
        <%= link_to(image_tag('cancel.png', :alt => t('mailboxer.delete'), :title => t('mailboxer.delete')),
                    conversation_path(conversation, :location => @box,
                                                    :box => @box,
                                                    :page => params[:page]),
                                                    :confirm => t('mailboxer.delete_confirm',
                                                                  :object => conversation.subject),
                                                    :method => :delete,
                                                    :remote => true) %>
      </div>
    <% end %>

    <div class="briefing">
      <%= raw(truncate(strip_tags(conversation.last_message.body), :length => 50)) %>
    </div>
  </div>
<% end %>

app/views/conversations/_conversation_full.html.erb
<h3>
  <%= conversation.subject %>
</h3>

<div class="action">
  <% unless @box.eql?'trash' %>
    <%= link_to(image_tag('cancel.png', :alt => t('mailboxer.delete'), :title => t('mailboxer.delete')),
      conversation_path(conversation, :location => 'conversation', :box => @box),
           :confirm => t('mailboxer.delete_confirm', :object => conversation.subject),
           :method => :delete, :remote => true) %>
  <% end %>
</div>

<h4>
  <%= t("message.participants") %>:
</h4>
<div class="participants">
  <% conversation.recipients.each do |recp| %>
    <%= link_to image_tag(recp.logo.url(:small), :title=>recp.name, :alt => recp.name), recp.subject %>
  <% end %>
</div>
<hr class="soften">
<div class="messages">
  <% @receipts.each do |receipt| %>
    <%= render receipt.message %>
  <% end %>

  <% unless @box.eql?'trash' %>
  <br>
  <%= form_tag conversation_path(conversation), :method => :put, :class => "cont_conversation" do %>
  <% if @receipt and @receipt.errors.any? %>
    <div class="error">
      <h2>
        <%= pluralize(@receipt.errors.count, "error") %> prohibited this message from being sent:
      </h2>
      <ul>
        <% @receipt.errors.full_messages.each do |msg| %>
        <li>
          <%= msg %>
        </li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="editor">
    <%= text_area_tag :body, nil,:rows =>6, :cols=> 53, :class => "required form_tag" %>
  </div>
  <div class="actions">
    <%= submit_tag t('mailboxer.reply'), :name => :reply_all,:class => "btn" %>
  </div>
  <% end %>
  <%end %>
</div>

<%= javascript_tag do %>
$(document).ready(function(){  
  $(".message .body img").each(function(){
    var link = '<a href=\"' + $(this).attr('src') + '\" class=\"img_link\"><img src=\"' + $(this).attr('src') + '\"></a>';
    $(this).after(link);
    $(this).remove();
    $(".message .body img").aeImageResize({ height: 490, width: 490 });
    $(".message .body a.img_link").lightBox({
      maxHeight: 920,
      maxWidth: 920,
      imageLoading: '../assets/lightbox-ico-loading.gif',
      imageBtnClose: '../assets/lightbox-btn-close.gif',
      imageBtnPrev: '../assets/lightbox-btn-prev.gif',
      imageBtnNext: '../assets/lightbox-btn-next.gif',
      imageBlank: '../assets/lightbox-blank.gif'
    });
  })  
});
<% end %> 

app/views/conversations/_index.html.erb
<div class="conversations">
  <%= render @conversations %>

  <%= render partial: 'layouts/more',
             locals: {
               path: conversations_path,
               per_page: 9,
               total: @conversations.total_count
            } %>
</div>

app/views/conversations/_show.html.erb
<div class="conversation_full">  
  <%= render :partial => 'conversation_full', :locals =>{:conversation => @conversation} %>
</div>

app/views/conversations/destroy.js.erb
$('#conversation_<%= @conversation.id %>').remove();

app/views/conversations/edit.html.erb
<% content_for :title do %>
  <%=t('message.other')%>
<% end %>

<h1>Editing message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/conversations/index.html.erb
<% content_for :title do %>
  <%=t('message.other')%>
<% end %>

<section id="conversations">

  <%= render partial: 'toolbar/messages' %>

  <%= render :partial => 'index' %>

  <%= javascript_tag do %>
    $(function() {
      SocialStream.Conversation.index();
    });
  <% end %>

</section>

app/views/conversations/index.js.erb
$("#content").html("<%=escape_javascript(render :partial => 'index') %>");
<%= location(link_to(image_tag("btn/message_" + @box + ".png", :class => "menu_icon")+t('message.' + @box), conversations_path(:box => @box),:remote => true)) %>

$('.pagination a').attr('data-remote', 'true');
	  
<%= toolbar :messages %>

app/views/conversations/show.html.erb
<% content_for :title do %>
  <%=t('message.other')%>
<% end %>

<section id="conversation">
  <%= render partial: 'toolbar/messages' %>

  <%= render :partial => 'show' %>

  <%= javascript_tag do %>
$('.cont_conversation').validate({errorClass: "validation_error"});
<% unless @box.eql?'trash' %>
  $("#body").cleditor({
    width:493,
    controls:  "<%= SocialStream.cleditor_controls %>"    
  });

		var message_hash = window.location.hash.match(/^.*message_(\d+).*$/);
		if (message_hash && message_hash.length > 0){
			$.scrollTo('#message_' + message_hash[1] ,1500,{axis:'y'});
		}else{
			$.scrollTo('#message_<%= @conversation.last_message.id %>',1500,{axis:'y'});		
		}
<% else %>
		var message_hash = window.location.hash.match(/^.*message_(\d+).*$/);
		if (message_hash && message_hash > 0){
			$.scrollTo('#message_' + message_hash[1] ,1500,{axis:'y'});
		}else{
			$.scrollTo('#message_<%= @conversation.last_message.id %>',1500,{axis:'y'});	
		}
<% end %>
<% end %>
</section>

app/views/conversations/show.js.erb
$("#content").html("<%= escape_javascript(render :partial => 'show') %>");

<%= toolbar :messages %>

$('.cont_conversation').validate({errorClass: "validation_error"});
<% unless @box.eql?'trash' %>
  $("#body").cleditor({
    width:493,
    controls:  "<%= SocialStream.cleditor_controls %>"     
  });

	var message_hash = window.location.hash.match(/^.*message_(\d+).*$/);
	if (message_hash && message_hash.length > 0){
		$.scrollTo('#message_' + message_hash[1] ,1500,{axis:'y'});
	}else{
		$.scrollTo('#message_<%= @conversation.last_message.id %>',1500,{axis:'y'});		
	}

<% else %>
	var message_hash = window.location.hash.match(/^.*message_(\d+).*$/);
	if (message_hash && message_hash.length > 0){
		$.scrollTo('#message_' + message_hash[1] ,1500,{axis:'y'});
	}else{
		$.scrollTo('#message_<%= @conversation.last_message.id %>',1500,{axis:'y'});		
	}
<% end %>