config/routes.rb
Rails.application.routes.draw do
  root :to => "frontpage#index"
  
  match 'home' => 'home#index', :as => :home
  match 'home' => 'home#index', :as => :user_root # devise after_sign_in_path_for
  match 'explore(/:section)' => 'explore#index', :as => :explore
  match 'search' => 'search#index', :as => :search

  # Social Stream subjects configured in config/initializers/social_stream.rb
  route_subjects do
    resources :contacts
    resource :like
    resource :profile
    resources :activities

    # Nested Social Stream objects configured in config/initializers/social_stream.rb
    #
    # /users/demo/posts
    (SocialStream.objects - [ :actor ]).each do |object|
      resources object.to_s.pluralize do
        get 'search', :on => :collection
      end
    end

    # Repository models are configured in config/initializers/social_stream.rb
    if SocialStream.repository_models.present?
      resource :repository do
        get 'search', on: :collection
      end
    end
  end

  resources :actors, only: [ :index ]

  # Get information about current_subject
  match 'user'    => 'users#current', format: :json

  match 'profile' => 'profiles#show'

  # Social Stream objects configured in config/initializers/social_stream.rb
  #
  # /posts
  (SocialStream.objects - [ :actor ]).each do |object|
    resources object.to_s.pluralize do
      get 'search', :on => :collection
    end
  end

  resources :comments

  # Repository models are configured in config/initializers/social_stream.rb
  if SocialStream.repository_models.present?
    resource :repository do
      get 'search', on: :collection
    end
  end

  resources :contacts do
    collection do
      get 'suggestion'
      get 'pending'
    end
  end

  namespace "relation" do
    resources :customs
  end

  resources :permissions

  resources :activity_actions

  resource :representation
  
  resources :settings do
    collection do
      put 'update_all'
    end
  end

  resources :messages

  resources :conversations

  resources :invitations
  
  resources :notifications do
    collection do
      put 'update_all'
    end
  end

  resources :activities do
    resource :like
  end

  get 'home/activities' => 'activities#index', as: :home_activities, defaults: { section: 'home' }

  get 'audience/index', :as => :audience
  
  match 'ties' => 'ties#index', :as => :ties
  
  match 'tags' => 'tags#index', :as => 'tags'
  
  ##API###
  match 'api/keygen' => 'api#create_key', :as => :api_keygen
  match 'api/user/:id' => 'api#users', :as => :api_user
  match 'api/me' => 'api#users', :as => :api_me
  match 'api/me/home/' => 'api#activity_atom_feed', :format => 'atom', :as => :api_my_home

  match 'api/me/contacts' => 'contacts#index', :format => 'json', :as => :api_contacts
  ##/API##
 
  #Background tasks
  constraints SocialStream::Routing::Constraints::Resque.new do
    mount Resque::Server, :at => "/resque"
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController

  before_filter :authenticate_user!
  before_filter :get_mailbox, :get_actor
  before_filter :check_current_subject_is_owner, :only => [:show, :update, :destroy]
  
  def index
    @notifications = @mailbox.notifications.not_trashed.page(params[:page]).per(10)
  end

  def show
    
  end

  def new

  end

  def edit

  end

  def create

  end

  def update
    if params[:read].present?
      if params[:read].eql?("Read")
        @actor.mark_as_read @notification
      elsif params[:read].eql?("Unread")
        @actor.mark_as_unread @notification
      end
    end
    @notifications = @mailbox.notifications.not_trashed.page(params[:page]).per(10)
    render :action => :index
  end
  
  def update_all
    @notifications= @mailbox.notifications.all
    @actor.mark_as_read @notifications

    if request.xhr?
      render text: ''
    else
      redirect_to notifications_path
    end
  end

  def destroy
    @notification.receipt_for(@actor).move_to_trash
    @notifications = @mailbox.notifications.not_trashed.page(params[:page]).per(10)
    render :action => :index
  end

  private

  def get_mailbox
    @mailbox = current_actor.mailbox
  end

  def get_actor
    @actor = Actor.normalize(current_subject)
  end


  def check_current_subject_is_owner
    
    @notification = Notification.find_by_id(params[:id])

    if @notification.nil? #TODO or !@notification.is_receiver?(@actor)
      redirect_to notifications_path
    return
    end
  end

end

app/helpers/notifications_helper.rb
module NotificationsHelper

  # An activity object title
  def title_of(act_obj)
    if act_obj.is_a? Comment
      'Re: ' + title_of(act_obj.parent_post)
    elsif act_obj.respond_to? :title and (not act_obj.title.nil?)
      act_obj.title.truncate(30, :separator => ' ')
    elsif act_obj.respond_to? :url and (not act_obj.url.nil?)
      act_obj.url.truncate(30, :separator => ' ')
    else I18n.t('notification.default')
    end
  end

  # An activity object description
  def description_of(act_obj)
    if act_obj.respond_to? :description and (not act_obj.description.nil?)
      sanitize(act_obj.description)
    else
      I18n.t('notification.watch_it')
    end
  end

  # Set locale as per subject preference
  def locale_as(subject)
    if subject.respond_to? :language
      I18n.locale = subject.language || I18n.default_locale
    end
  end

  # Add notification_id param to URL in order to mark notification read
  def notification_url_of(target, notification)
    return polymorphic_url(target, :notification_id => notification.id) unless notification.nil?
    polymorphic_url(target)
  end

end

app/views/notifications/_index.html.erb
<div class="notifications">
  <h1 class="colorfont">
    <%= t('notification.other') %>
  </h1>

  <div class="read_all">
    <%= link_to(t('notification.read_all'), update_all_notifications_path(:page => params[:page]),
        :method => :put, class: 'mark_as_read') %>
  </div>

  <div class="list"> 
    <% @notifications.each do |notification|%>
      <% @notification = notification %>
      <% read_class = notification.is_unread?(@actor) ? 'unread' : '' %>
      <%= render :partial => 'notification', :object => notification, :locals => {:read_class => read_class} %>
    <% end %>
  </div>
  <%= javascript_tag do %>
    $(function() {
      SocialStream.Notification.index();
    });
  <% end %>
</div>

app/views/notifications/_notification.html.erb
<%= div_for(notification, :class => read_class + ' conversation') do %>

<tr>
  <td>
    <%= div_for(notification) do %>
      <i class="icon_navbar-notification"></i><!-- este icono debe de ser cambiado por la tipologia que le corresponda segun el contenido-->
      <%= render :partial => "notifications/activities/#{ notification.notified_object.verb }",
                 :locals => {:activity => notification.notified_object} %>
      
    <% end %>
    <span class="date-ago"><%= t('time.ago', :time => time_ago_in_words(notification.created_at)) %></span>
  </td>
</tr>

<% end %>

app/views/notifications/index.html.erb
<% content_for :title do %>
  <%= current_subject.name %>
<% end %>

<section id="notifications">

  <%= render partial: 'toolbar/home'  %>

  <%= render :partial => 'index' %>

  <%= render partial: 'sidebar/show' %>
</section>

app/views/notifications/index.js.erb
$("#content").html("<%=escape_javascript(render :partial => 'index') %>");
$("header").html("<%=escape_javascript(render :partial => 'layouts/header') %>");

<%= location(link_to(t('notification.other'), notifications_path,:remote => true)+' ('+@mailbox.notifications.not_trashed.unread.count.to_s+')') %>

$('.pagination a').attr('data-remote', 'true');