config/routes.rb
Rails.application.routes.draw do
  root :to => "frontpage#index"
  
  match 'home' => 'home#index', :as => :home
  match 'home' => 'home#index', :as => :user_root # devise after_sign_in_path_for
  match 'explore(/:section)' => 'explore#index', :as => :explore
  match 'search' => 'search#index', :as => :search

  # Social Stream subjects configured in config/initializers/social_stream.rb
  route_subjects do
    resources :contacts
    resource :like
    resource :profile
    resources :activities

    # Nested Social Stream objects configured in config/initializers/social_stream.rb
    #
    # /users/demo/posts
    (SocialStream.objects - [ :actor ]).each do |object|
      resources object.to_s.pluralize do
        get 'search', :on => :collection
      end
    end

    # Repository models are configured in config/initializers/social_stream.rb
    if SocialStream.repository_models.present?
      resource :repository do
        get 'search', on: :collection
      end
    end
  end

  resources :actors, only: [ :index ]

  # Get information about current_subject
  match 'user'    => 'users#current', format: :json

  match 'profile' => 'profiles#show'

  # Social Stream objects configured in config/initializers/social_stream.rb
  #
  # /posts
  (SocialStream.objects - [ :actor ]).each do |object|
    resources object.to_s.pluralize do
      get 'search', :on => :collection
    end
  end

  resources :comments

  # Repository models are configured in config/initializers/social_stream.rb
  if SocialStream.repository_models.present?
    resource :repository do
      get 'search', on: :collection
    end
  end

  resources :contacts do
    collection do
      get 'suggestion'
      get 'pending'
    end
  end

  namespace "relation" do
    resources :customs
  end

  resources :permissions

  resources :activity_actions

  resource :representation
  
  resources :settings do
    collection do
      put 'update_all'
    end
  end

  resources :messages

  resources :conversations

  resources :invitations
  
  resources :notifications do
    collection do
      put 'update_all'
    end
  end

  resources :activities do
    resource :like
  end

  get 'home/activities' => 'activities#index', as: :home_activities, defaults: { section: 'home' }

  get 'audience/index', :as => :audience
  
  match 'ties' => 'ties#index', :as => :ties
  
  match 'tags' => 'tags#index', :as => 'tags'
  
  ##API###
  match 'api/keygen' => 'api#create_key', :as => :api_keygen
  match 'api/user/:id' => 'api#users', :as => :api_user
  match 'api/me' => 'api#users', :as => :api_me
  match 'api/me/home/' => 'api#activity_atom_feed', :format => 'atom', :as => :api_my_home

  match 'api/me/contacts' => 'contacts#index', :format => 'json', :as => :api_contacts
  ##/API##
 
  #Background tasks
  constraints SocialStream::Routing::Constraints::Resque.new do
    mount Resque::Server, :at => "/resque"
  end
end

app/models/group.rb
# {Group Groups} are the other kind of social entities supported in SocialStream::Base
#
# As with {User}, almost all the interaction with other classes in Social Stream is done
# through {Actor}. The glue between {Group} and {Actor} is in {SocialStream::Models::Subject}
#
class Group < ActiveRecord::Base
  include SocialStream::Models::Subject

  attr_accessor :owners

  delegate :description, :description=, :to => :profile!

  after_create :create_ties

  def profile!
    actor!.profile || actor!.build_profile
  end
 
  private

  # Creates ties from founder to the group, based on _relation_ids,
  # and ties from the group to founder and owners.
  def create_ties
    create_ties_from_author
    create_ties_to_owners
  end

  # Creates the ties from the founder to the group
  def create_ties_from_author
=begin
    # FIXME: need to define a proper relation for this case. Maybe a system defined relation
    author.sent_contacts.create! :receiver_id  => actor_id,
                                 :relation_ids => _relation_ids

    if represented_author?
      user_author.sent_contacts.create! :receiver_id  => actor_id,
                                        :relation_ids => _relation_ids
    end
=end
  end
  
  # Creates the ties from the group to the owners added in the group creation form
  #
  # The system-defined Relation::Owner is used for the ties
  def create_ties_to_owners
    @owners ||= ""

    owner_ids = ([ author_id, user_author_id ] | @owners.split(',').map(&:to_i)).uniq

    owner_ids.each do |a|
      c =
        sent_contacts.create! :receiver_id  => a,
                              :user_author  => user_author
      
      c.relation_ids = Array.wrap(::Relation::Owner.instance.id)
    end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  include SocialStream::Controllers::Subjects
  include SocialStream::Controllers::Authorship

  before_filter :authenticate_user!, :except => [ :index, :show ]

  load_and_authorize_resource except: :index

  respond_to :html, :js

  def index
    raise ActiveRecord::RecordNotFound
  end

  def create
    create! do |success, failure|
      success.html {
        self.current_subject = resource

        flash[:notice] += t('representation.notice',
                             :subject => resource.name)

        redirect_to :home
      }
    end
  end

  def destroy
    destroy! do |success, failure|
      success.html {
        self.current_subject = current_user
        redirect_to :home
      }
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper

end

app/views/groups/_form.html.erb
<%= form_for group, html: { class: 'ss_group_form' } do |f| %>
  <% if group.errors.any? %>
    <div class="error">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>
      <ul>
        <% group.errors.full_messages.each do |msg| %>
          <li>
          <%= msg %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <section class="name">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </section>
  <section class="owners">
    <%= f.label :owners %>
    <%= f.hidden_field :owners, 'data-path' => actors_path(format: :json), "data-actor_name" => current_subject.name %>
  </section>
  <section class="tags">
    <%= f.label :tags_list %>
    <%= f.text_field :tag_list, 'data-path' => tags_path(format: :json) %>
  </section>
  <section class="description">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </section>

  <%= f.submit :class => "btn" %>
<% end %>

<%= javascript_tag do %>
  $(function() {
    SocialStream.Group.new_(
      {
        form: '.ss_group_form',
        validate: [
          {
            errorClass: "validation_error"
          }
        ]
      }
    );
  });
<% end %>

app/views/groups/_group.html.erb
<%= render partial: 'subjects/subject',
           object:  group %>

app/views/groups/_index.html.erb
<% cont=0; %>
<% @groups.each do |group| %>
<% if (cont%2) == 0 %>
<% cont+=1; %>
<div class="row">
  <% end %>
  <div class="label">
    <%= render group %>
  </div>
  <% if ((cont%2) == 0) 	%>
</div>
<% end %>
<% end %>
<% if ((cont%2) != 0) 	%> <div class="label"></div>
</div>
<% end %>
<div class="row">
  <%= paginate @groups %>
</div>

app/views/groups/_new_modal.html.erb
<div id="new_group-modal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="new_group-modal-title" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="new_group-modal-title"><%= t 'group.new.title' %></h3>
  </div>
  <div class="modal-body">
    <%= render partial: 'groups/form',
               object: resource_class.new(owners: current_subject.actor_id),
               as: :group %>
  </div>
</div>

app/views/groups/_quick_search_result.html.erb
<%= render group %>

app/views/groups/_search_result.html.erb
<%= render group %>

app/views/groups/_show.html.erb
<section id="group">
  <%= render partial: 'toolbar/profile', locals: { subject: @group } %>

  <%= render :partial => "activities/index",
             :locals  => { section: @group,
                           owner:   @group } %>

  <%= render partial: 'sidebar/show' %>
</section>

app/views/groups/_timeline.html.erb
<%= render partial: 'subjects/timeline',
           object: group,
           as: :subject %>

app/views/groups/index.js.erb
$('#list_users_ajax').html("<%= escape_javascript(render :partial => "groups/index") %>");

app/views/groups/new.html.erb
<section id="new_group">
  <% content_for :title do%>
    <%= t('group.new.action')%>
  <%end%>

  <%= render partial: 'toolbar/home' %>

  <h2><%= t('group.new.title') %></h2>

  <%= render partial: 'form',
             object: resource_class.new(owners: current_subject.actor_id),
             as: :group %>
</section>

app/views/groups/show.html.erb
<% content_for :title do %>
  <%= "#{ resource.name } | #{ t 'site.name' }" %>
<% end %>

<% content_for :description do %>
  <% if resource.profile.description? %>
    <%= resource.profile.description%>
  <% else %>
    <%= "#{ resource.name } #{ t 'profile.is_on' } #{ t 'site.name' }" %>
  <% end %>
<% end %>

<% content_for :keywords do %>
  <%= resource.tag_list%>
<% end %>

<%= render :partial => 'show' %>

app/views/groups/show.js.erb
<%= render :partial => 'subjects/show',
           :locals  => { :subject => @group } %>